### ISSUE TITLE
Test environment cannot be found.

### ISSUE THREAD

**Issue by ellisio** [theneva/jest-environment-jsdom-12#1]
I am trying to use this package to get `jsdom@12` into our test environment for shadow testing, since this is not supported in 11 and below.

I have installed this package, and it's showing up in my `node_modules`. However, if I set the following in my `jest.config.js`:

```
testEnvironment: 'jest-environment-jsdom-twelve',
```

I get the following error when trying to run tests:

```
● Validation Error:

  Test environment jest-environment-jsdom-twelve cannot be found. Make sure the testEnvironment configuration option points to an existing node module.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

I have also tried using `jsdom-twelve`, since Jest uses `jsdom` as their default and their package is called `jest-environment-jsdom`. Still no luck.

Environment:
```
node v10.15.1
npm v6.8.0
jest v24.1.0
```

**Comment by theneva** [comment]
Hi @ellisio! Thank you for your issue and sorry about the late reply.

This repo is deprecated in favour of https://github.com/theneva/jest-environment-jsdom-thirteen which uses JSDOM 13 (yay for version numbers in package names). I recommend upgrading to that package!

If you're still interested in what caused this:

Version 0.0.3 of this package was published without having compiled the code first… Sorry about that! 😅 

To prevent this from happening again in this repo, I added a prepublish script that builds the package before publish in c685012. I'll do the same in jest-environment-jsdom-thirteen.

I've also released a version 0.0.4 of this package with a proper build directory that seems to work for me. If you for whatever reason can't use jest-environment-jsdom-thirteen, at least you can upgrade this package to version 0.0.4 😃

**Comment by ellisio** [comment]
@theneva Thank you for the follow up! I switched back to Mocha and Chai for the time being as I had it working under that world. But with this knowledge, I'll add an item to our backlog to get us over to Jest finally. 🎉 🎉

**Comment by theneva** [comment]
@ellisio cool! There's yet another new package with JSDOM 14 now (not maintained by me—I guess I was too slow): http://npm.im/jest-environment-jsdom-fourteen

**Comment by ellisio** [comment]
@theneva you should get ahead of the curve and start a new package that has these versioned under semantic versioning. I would love you forever since I wouldn't have to keep track with new projects due to package names containing the version. 💩

**Comment by theneva** [comment]
If you have any ideas for a good package name I'm all ears @ellisio :smile:

The original package from the Jest project is called [jest-environment-jsdom](https://www.npmjs.com/package/jest-environment-jsdom), and [jest-environment-jsdom-latest](http://npm.im/jest-environment-jsdom-latest) is already taken, which is why I ended up just naming the original `-jsdom-twelve`. I wasn't expecting three major releases of JSDOM in such a short time!

Anyway, Node 6 moves to end of life in April, so it's likely that the next major version of Jest will drop Node 6 and support newer JSDOM versions, effectively removing the need for these third party packages.
